import Head from 'next/head';
import Navbar from '../src/componentes/Navbar';
import Footer from '../src/componentes/Footer';

export default function Home() {
  return (
    <>
      <Head>
        <title>Lista de tarefas</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />
      
      <section id='banner'>
        <div id="carouselExampleSlidesOnly" className="carousel slide" data-bs-ride="carousel">
          <div className="carousel-inner">
            <div className="carousel-item active">
              <img src="to-do-list.jpg" className="d-block w-100" alt="..." />
            </div>
          </div>
        </div>
      </section>

      <section id='ultimas-tarefas'>
        <div className='container'>
          <h1 className='titulo'>Últimas tarefas</h1>

          <div>
            <div className="card">
              <div className="card-body">
                <h5 className="card-title">Lorem ipsum</h5>
                <p className="card-text">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum non ante quis odio laoreet tincidunt.</p>
              </div>
            </div>

            <div className="card">
              <div className="card-body">
                <h5 className="card-title">Lorem ipsum</h5>
                <p className="card-text">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum non ante quis odio laoreet tincidunt.</p>
              </div>
            </div>

            <div className="card">
              <div className="card-body">
                <h5 className="card-title">Lorem ipsum</h5>
                <p className="card-text">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum non ante quis odio laoreet tincidunt.</p>
              </div>
            </div>
          </div>
        </div>
      </section>

      <Footer />

    </>
  )
}
